### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Foreveryoon** [chenbinghui1/DSL#10]
你好，我在用多gpu分布式训练网络时，DistSamplerSeedHook_semi出现了如下错误：
![dsl_1](https://user-images.githubusercontent.com/106503278/170917362-5811612e-33b5-4d9e-a807-bba19e50ffb0.png)
![dsl_2](https://user-images.githubusercontent.com/106503278/170917368-c7414642-aa20-448d-8876-efe79ae4a648.png)
请问是什么原因呢

**Comment by chenbinghui1** [comment]
@Foreveryoon 暂时没有遇到过这个问题，可以debug一下看看对应的dataloader中的内容，是否正确；以及是否是按照readme的config训练的，可能自己修改了config或者代码 导致的不兼容

**Comment by Foreveryoon** [comment]
请问能分享一下训练好的模型吗， 我想测试一下

**Comment by chenbinghui1** [comment]
@Foreveryoon 好的 我整理下 把模型放出来

**Comment by chenbinghui1** [comment]
@Foreveryoon hi，预训练模型已经全部release了，欢迎测试~祝好
