### ISSUE TITLE
Question about dsl

### ISSUE THREAD

**Issue by heiyuxiaokai** [chenbinghui1/DSL#16]
Must the supervised model be trained in advance? Can I use DSL to train a model both with labeled samples and unlabeled samples from the begining(just with pretrained model of backbone)?

**Comment by chenbinghui1** [comment]
@heiyuxiaokai Yeah, the supervised model should be trained first so as to produce the initial pseudo-labels. This will encourage the better performances.

**Comment by heiyuxiaokai** [comment]
> @heiyuxiaokai Yeah, the supervised model should be trained first so as to produce the initial pseudo-labels. This will encourage the better performances.

I get it, and thanks!
