### ISSUE TITLE
How the scale invariant implement?

### ISSUE THREAD

**Issue by Zhangjiacheng144** [chenbinghui1/DSL#19]
非常感谢您能开源您的代码！不过我在阅读您的代码的时候有几个地方不是很明白，所以想请教您一下：
1. 关于Adaptive Threshold，我看到您的实现代码里稍微跟Paper有一些不一样的地方，可以麻烦您稍微解释一下吗？
![image](https://user-images.githubusercontent.com/51013927/183892651-9f66975b-811c-4dd3-b90e-d76b58df23b7.png)
2. 关于Scale Invariant Learning，我没有看懂您这一部分的实现原理，您是对unlabel image进行缩放，然后一起加载进来的吗？一个batch的数据是怎么组织的呢？我看您的代码只看到如何组织label image和unlabel image，不知道这个缩放的图片是如何加载进来和组织的呢？这里的`flatten_As_labels`是用来干什么的呢？
![image](https://user-images.githubusercontent.com/51013927/183893701-9c935e64-1549-4372-9677-face7c4e2675.png)
3. 关于这个Ignore，我理解这里应该是想把那些原本被那些高质量的伪标签分配为背景的Proposal/ Anchor Box，通过ignore gt box，分配得到ignore label，从而不计算这些Proposal/Anchor Box的loss. 但是看您这里的逻辑如果一个Proposal/Anchor Box被ignore gt box或者gt box分配了背景类标签，即flatten_ig_labels - self.num_classes = 0，flatten_labels - self.num_classes = 0，这个Proposal/Anchor Box对应的sample wise的权重则会置为0，这是不是不合理呢？
![image](https://user-images.githubusercontent.com/51013927/183895245-26e0e467-ce51-4606-9125-21b395a4e569.png)

**Comment by chenbinghui1** [comment]
@Zhangjiacheng144 
1. 这里算的是平均的类别Npos数，其实为的是更加稳定一些，以及不同类别可以归一化对比这样的目的。
2. 如果采用scale_invariant_loss，会先在batch读入之前，对batch中最后一个unlabel数据进行缩放，并重新加到batch中，所以会是奇数大小的batch，具体实现在这里 
 https://github.com/chenbinghui1/DSL/blob/4c2e6f3c5ffcc18ed874061f054da9779a2f736d/mmdet/runner/hooks/semi_epoch_based_runner.py#L186-L204

如论文中说到的会对label unlabel数据进行不同的加权，flatten_As_label就是这个目的，最后当作一个weight乘到整体的loss计算中，

3. 首先ig_labels 在之前已经计算完毕了；您截图的这部分仅仅是处理flatten_ig_labels flatten_labels 都不为背景的情况；如果有一个是背景了，这里都是不会操作的；

**Comment by Zhangjiacheng144** [comment]
非常感谢您的回复！我明白了，这个scale invariant是每个batch只对batch中的最后一张unlabel image进行的是吗？想问一下为什么没有考虑对整个unlabel image batch进行呢？这是出于什么特殊的考虑吗？

**Comment by chenbinghui1** [comment]
@Zhangjiacheng144   主要是为了和其他论文对齐，batch 采用2(per_gpu)*8(gpus)=16这么大。所以只需要对最后一张操作就可以了。目前代码支持per_gpu=2的 更大的数值，其他数值的 我自己还没有跑过。

**Comment by Zhangjiacheng144** [comment]
好的，谢谢您的解答，非常感谢！
