### ISSUE TITLE
 local variable 'save_path' referenced before assignment

### ISSUE THREAD

**Issue by qianying-zd** [chenbinghui1/DSL#21]
![local variable 'save_path' referenced before assignment](https://user-images.githubusercontent.com/80744120/184643719-9a870a90-6754-49b2-a7b6-3d1e35433035.png)

**Comment by chenbinghui1** [comment]
@qianying-zd  please strictly follow the demo configs, and add '/' at the end of path or prefix and so on
https://github.com/chenbinghui1/DSL/blob/4c2e6f3c5ffcc18ed874061f054da9779a2f736d/configs/fcos_semi/RLA_r50_caffe_mslonger_tricks_0.Xdata_unlabel_dynamic_lw_nofuse_iterlabel_si-soft_singlestage.py#L129-L131
