### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by BowieHsu** [chenbinghui1/DSL#22]
Hi, binghui, thank you for sharing your work, I also work on ssod area, I found some differences between your work and other opensource ssod architecher, since the problem I will describe should be very specific, to prevent misunderstanding, I write them in chinese:
1.我仔细看了你代码的实现，在做10%standard任务时，大概的状态是你会在半监督那部分开始之前，用10%数据量训练好的模型来生成一份伪标签，然后在半监督的时候，你每个epoch的的迭代次数其实是按照这个伪标签的图片数量来的，是这样吗？
2.你的伪标签在每一个epoch结束后利用pred_hook机制又重新生成一次，同时是每个epoch来更新你的af模块，如果我没有理解错的话，你的ema模型是每一个迭代都会更新，但是只会在epoch结束来ema离线生成伪标签，这个与我们自己实现的方案有点不同，我们是利用ema每个迭代生成伪标签而且ema也每个迭代更新，道理上来说我感觉你这种方式貌似更加鲁棒，这样的实现有什么原因吗？
感谢你的工作并期待你的回复。

**Comment by chenbinghui1** [comment]
@BowieHsu 你好，感谢对我们工作的关注~
1. 是的半监督开始前，会进行有标注数据的初步训练，得到一个不错的初始模型，这个也是所有半监督算法都会做的，只不过是实现的方式是显式地two-stage（我们采用的）还是隐式地two-stage（即通过在training阶段用开关控制是否开启无标注数据的训练）；另外epoch的迭代次数是和有标注数据集以及无标注数据集两个都有关的，只不过无标注数据的数量一般都远大于有标注数据。一个epoch表示将最大数量的数据集过一遍；
2. 伪标签的更新等是用 pred_hook机制来更新，不过我们提供了epoch-based 和iter-based的方案，可以通过config的这个地方来进行修改
https://github.com/chenbinghui1/DSL/blob/4c2e6f3c5ffcc18ed874061f054da9779a2f736d/configs/fcos_semi/RLA_r50_caffe_mslonger_tricks_0.Xdata_unlabel_dynamic_lw_nofuse_iterlabel_si-soft_singlestage.py#L163

1%-10%数据协议下采用的都是iter-based的方案，即每个iter结束的时候会更新一下 下一个iter要训练的图片的伪标签（这个由于mmdet hook机制，为了全部采用hook来实现，所以如此设计，并没有仿照其他框架在每个iter的时候先对输入图片打伪标签的方式，但其实是等价的。）

AF的阈值是每个epoch更新即可，因为阈值的iter和epoch-based的更新 其实影响没那么大（至少在我的实验中是这样的）；

ema模型的更新是基于iter进行；

当然上面介绍的伪标签更新是基于iter的方案， 我们也支持epoch的方案，就如同你讲到的，每个epoch结束更新一下所有无标注数据的标签；

**Comment by BowieHsu** [comment]
@chenbinghui1 感谢回复，您说的情况我了解了，您的讲解很有帮助，我们目前是在yolov5框架的基础上添了半监督的东西，但是现在的效果不太好，只能稍微涨2、3个点，所以想看看大家在单阶段检测器上都是怎么做的，现在有两个怀疑点是
1.在线生成伪标签时没有动态阈值 
2.算loss时没有ignore target，只有正负targets，就是单纯把所有大于阈值生出来的伪标签当作正样本了
从您这边一系列实验下来的感觉，我的这些猜测点有道理么？或者这两个点哪个的影响会更大一些呢？

**Comment by chenbinghui1** [comment]
@BowieHsu 对于第一个怀疑点可以后面再试，我这边的感觉就是动态阈值可能有用但是不会特别多，另外第二个怀疑点比较关键，也正如我们论文中提到的，密集的检测器，ignore label还是比较关键的，至少在我这边是这样的（包括学术集，和业务数据集）；当然ignore-label也可以变形，例如通过添加一个weight来操作（ignore-label可以理解为 hard方式，weight可以理解为soft方式）；
