### ISSUE TITLE
关于半监督训练的一些问题

### ISSUE THREAD

**Issue by Skyninth** [chenbinghui1/DSL#23]
您好，看了您的工作，提出了很多新的想法，感觉收益很多。
        我想要问一下，对于半监督训练，在监督训练baseline的时候需要将模型训练至完全收敛吗，还是要留存出一定的空间至没有完全收敛状态，因为在半监督阶段也会使用到标注的数据，从而防止这部分数据的过拟合而影响到模型的整体效果。
        因为我看您说一般baseline在55epoch达到较好效果，我用voc数据训练了60epoch后到达63.8AP50，而您论文中给出的supervised的AP50是69.6。所以说是不是在监督阶段留一部分余量会更好？

**Comment by chenbinghui1** [comment]
@Skyninth 首先感谢对我们工作的认可~
【1】在监督训练的时候，其实训练到完全收敛是最好的（完全收敛指的是在val上性能最佳的，如果训练太久可能本身就已经过拟合了，例如VOC上我发现55的 要比60 70 甚至80的 val result高，因为本身数据少，容易过拟合，当第一次降低lr时候究竟可能早的终止训练，后面继续训练大概率会过拟合），这样做的好处是：model用于unlabel数据的时候，可以提供更好的初始伪标签。
【2】至于收敛到最好的model在后续unlabel加入之后是否会过拟合的 问题，答案是不会的，因为1）有大量的unlabel数据加入，model模拟的特征空间会严重变化，此时是不会过拟合那一丢丢监督数据的 2）后续训练的lr是从0.01开始，即最大lr开始的，这个时候模型同样不会过拟合，因为step特别大，只有lr小的时候一般才发生过拟合。

【3】至于性能对比方面：其实我自己的经验是监督数据部分模型性能差不多就行了，初实supervised model高一个点两个点的其实对最终加入大量无标签数据训练后的结果影响不大，因为后续依然会对标签进行动态更新的 。

**Comment by Skyninth** [comment]
> @Skyninth 首先感谢对我们工作的认可~ 【1】在监督训练的时候，其实训练到完全收敛是最好的（完全收敛指的是在val上性能最佳的，如果训练太久可能本身就已经过拟合了，例如VOC上我发现55的 要比60 70 甚至80的 val result高，因为本身数据少，容易过拟合，当第一次降低lr时候究竟可能早的终止训练，后面继续训练大概率会过拟合），这样做的好处是：model用于unlabel数据的时候，可以提供更好的初始伪标签。 【2】至于收敛到最好的model在后续unlabel加入之后是否会过拟合的 问题，答案是不会的，因为1）有大量的unlabel数据加入，model模拟的特征空间会严重变化，此时是不会过拟合那一丢丢监督数据的 2）后续训练的lr是从0.01开始，即最大lr开始的，这个时候模型同样不会过拟合，因为step特别大，只有lr小的时候一般才发生过拟合。
> 
> 【3】至于性能对比方面：其实我自己的经验是监督数据部分模型性能差不多就行了，初实supervised model高一个点两个点的其实对最终加入大量无标签数据训练后的结果影响不大，因为后续依然会对标签进行动态更新的 。

好的，感谢您的答复！
