### ISSUE TITLE
我想请问一下为什么跑这个程序会直接卡死

### ISSUE THREAD

**Issue by PilgrimGrey1** [chenbinghui1/DSL#29]
在For COCO Partially Labeled Data protocol，中的第四步执行脚本时，
<img width="1555" alt="截屏2023-03-10 16 33 27" src="https://user-images.githubusercontent.com/100546897/224265973-56e3a9fa-37ac-4c2a-ab38-60f9e9d990c7.png">
下面是我的环境配置：
<img width="1582" alt="截屏2023-03-10 16 35 49" src="https://user-images.githubusercontent.com/100546897/224266119-68e79b6b-c2e0-4ed2-9d05-0ab32a3a57f3.png">

我在index created停了很久了，没有其他的报错，但是就是卡住了，这是什么原因呢？可以帮我解决一下吗？

**Comment by PilgrimGrey1** [comment]
> 在For COCO Partially Labeled Data protocol，中的第四步执行脚本时， <img alt="截屏2023-03-10 16 33 27" width="1555" src="https://user-images.githubusercontent.com/100546897/224265973-56e3a9fa-37ac-4c2a-ab38-60f9e9d990c7.png"> 下面是我的环境配置： <img alt="截屏2023-03-10 16 35 49" width="1582" src="https://user-images.githubusercontent.com/100546897/224266119-68e79b6b-c2e0-4ed2-9d05-0ab32a3a57f3.png">
> 
> 我在index created停了很久了，没有其他的报错，但是就是卡住了，这是什么原因呢？可以帮我解决一下吗？

问题已经得到解决，版本问题

**Comment by PilgrimGrey1** [comment]
在跑baseline的过程中，训练结果差劲，这种情况正常吗？
<img width="1597" alt="截屏2023-03-11 10 21 42" src="https://user-images.githubusercontent.com/100546897/228190105-7d4b6677-b9cf-4042-9247-ac53f68b8fb4.png">

**Comment by chenbinghui1** [comment]
@PilgrimGrey1 请问使用的多少比例的数据 不同比例标注数据的max_epoch 以及steps请参考config里面的注释，并进行相应修改 
https://github.com/chenbinghui1/DSL/blob/f06a4112fd708185323363891df1e3d938982b19/configs/fcos_semi/r50_caffe_mslonger_tricks_0.Xdata.py#L134-L141
例如  0.01/0.02 data 150-180-200  表示 最大max_epoch200 steps设置为[150,180]

**Comment by PilgrimGrey1** [comment]
> @PilgrimGrey1 请问使用的多少比例的数据 不同比例标注数据的max_epoch 以及steps请参考config里面的注释，并进行相应修改
> 
> https://github.com/chenbinghui1/DSL/blob/f06a4112fd708185323363891df1e3d938982b19/configs/fcos_semi/r50_caffe_mslonger_tricks_0.Xdata.py#L134-L141
> 
> 
> 例如 0.01/0.02 data 150-180-200 表示 最大max_epoch200 steps设置为[150,180]

十分感谢答疑解惑！我使用的就是默认的，10%的coco训练数据，

**Comment by PilgrimGrey1** [comment]
> @PilgrimGrey1 请问使用的多少比例的数据 不同比例标注数据的max_epoch 以及steps请参考config里面的注释，并进行相应修改
> 
> https://github.com/chenbinghui1/DSL/blob/f06a4112fd708185323363891df1e3d938982b19/configs/fcos_semi/r50_caffe_mslonger_tricks_0.Xdata.py#L134-L141
> 
> 
> 例如 0.01/0.02 data 150-180-200 表示 最大max_epoch200 steps设置为[150,180]

能否看看原实验结果数据

**Comment by chenbinghui1** [comment]
@PilgrimGrey1 
     4, loss_bbox: 0.0753, loss_centerness: 0.5994, loss: 0.6971
7888 2022-05-20 03:42:27,798 - mmdet - INFO - Epoch [100][680/734]   lr: 1.000e-04, eta: 0:00:26, time: 0.476, data_time: 0.029, memory: 3321, loss_cls: 0.025     9, loss_bbox: 0.0816, loss_centerness: 0.5996, loss: 0.7071
7889 2022-05-20 03:42:32,397 - mmdet - INFO - Epoch [100][690/734]   lr: 1.000e-04, eta: 0:00:21, time: 0.458, data_time: 0.028, memory: 3321, loss_cls: 0.024     4, loss_bbox: 0.0800, loss_centerness: 0.5983, loss: 0.7027
7890 2022-05-20 03:42:37,165 - mmdet - INFO - Epoch [100][700/734]   lr: 1.000e-04, eta: 0:00:16, time: 0.479, data_time: 0.030, memory: 3321, loss_cls: 0.022     0, loss_bbox: 0.0751, loss_centerness: 0.5962, loss: 0.6933
7891 2022-05-20 03:42:41,988 - mmdet - INFO - Epoch [100][710/734]   lr: 1.000e-04, eta: 0:00:11, time: 0.478, data_time: 0.027, memory: 3321, loss_cls: 0.023     7, loss_bbox: 0.0834, loss_centerness: 0.5999, loss: 0.7070
7892 2022-05-20 03:42:46,513 - mmdet - INFO - Epoch [100][720/734]   lr: 1.000e-04, eta: 0:00:06, time: 0.451, data_time: 0.031, memory: 3321, loss_cls: 0.024     0, loss_bbox: 0.0805, loss_centerness: 0.5975, loss: 0.7020
7893 2022-05-20 03:42:51,128 - mmdet - INFO - Epoch [100][730/734]   lr: 1.000e-04, eta: 0:00:01, time: 0.465, data_time: 0.033, memory: 3321, loss_cls: 0.026     6, loss_bbox: 0.0829, loss_centerness: 0.5983, loss: 0.7077
7894 2022-05-20 03:42:54,747 - mmdet - INFO - Saving checkpoint at 100 epochs
7895 2022-05-20 03:44:59,644 - mmdet - INFO - Evaluating bbox...
7896 2022-05-20 03:45:35,701 - mmdet - INFO - Exp name: r50_caffe_mslonger_tricks_0.Xdata.py
7897 2022-05-20 03:45:35,701 - mmdet - INFO - Epoch(val) [100][625]  bbox_mAP: 0.2250, bbox_mAP_50: 0.3780, bbox_mAP_75: 0.2320, bbox_mAP_s: 0.1060, bbox_mAP_     m: 0.2430, bbox_mAP_l: 0.3010, bbox_mAP_copypaste: 0.225 0.378 0.232 0.106 0.243 0.301

**Comment by PilgrimGrey1** [comment]
<img width="1585" alt="截屏2023-03-30 11 05 43" src="https://user-images.githubusercontent.com/100546897/228718261-fb6ace46-aaa5-4fb1-b810-6b9a68a301f4.png">
我想了很久，配置信息都没错，就只有可能环境有问题，导致训练过程出错，考虑到我的cuda版本比较新，我使用的mmcv也应该比较新，所以我又重新配了一遍环境，这个结果似乎正常了一点，但是还是没达到论文中的结果，我想问一下，硬件会影响训练结果吗？

**Comment by PilgrimGrey1** [comment]
我使用的是两张3090

**Comment by chenbinghui1** [comment]
@PilgrimGrey1  可以试试修改lr 以及warmup （warmup可以修改成500x4）;lr的话 不知道mmdet新的版本有没有修改哈 原来是和卡的个数有关的，8卡对应0.01或者0.02 如果4卡 或者更少的话 lr需要减小 当然 目前 看你这个结果貌似lr问题不大；

**Comment by PilgrimGrey1** [comment]
> @PilgrimGrey1 可以试试修改lr 以及warmup （warmup可以修改成500x4）;lr的话 不知道mmdet新的版本有没有修改哈 原来是和卡的个数有关的，8卡对应0.01或者0.02 如果4卡 或者更少的话 lr需要减小 当然 目前 看你这个结果貌似lr问题不大；

这个结果偏向正常吗？

**Comment by PilgrimGrey1** [comment]
> @PilgrimGrey1 可以试试修改lr 以及warmup （warmup可以修改成500x4）;lr的话 不知道mmdet新的版本有没有修改哈 原来是和卡的个数有关的，8卡对应0.01或者0.02 如果4卡 或者更少的话 lr需要减小 当然 目前 看你这个结果貌似lr问题不大；

确实，卡少的话，一个epoch迭代次数就多，学习率应该调小一点，我试试诶

**Comment by chenbinghui1** [comment]
> > @PilgrimGrey1 可以试试修改lr 以及warmup （warmup可以修改成500x4）;lr的话 不知道mmdet新的版本有没有修改哈 原来是和卡的个数有关的，8卡对应0.01或者0.02 如果4卡 或者更少的话 lr需要减小 当然 目前 看你这个结果貌似lr问题不大；
> 
> 这个结果偏向正常吗？

19.x效果应该接近正常了 可能确实是卡数量带来的config中 lr 或者warmup以及其他配置项不适配的问题

**Comment by PilgrimGrey1** [comment]
我准备去修改每个epoch的训练流程，发现源代码semi_epoch_based_runner.py中的run函数在进行epoch循环的时候有问题：
<img width="642" alt="截屏2023-05-17 00 28 23" src="https://github.com/chenbinghui1/DSL/assets/100546897/ba2067ab-3d34-402b-82bc-e91cc62fa2cc">
每次执行该文件夹下的train函数的时候，是self._epoch+=1，但在run函数中，是拿self.epoch进行判定，程序执行却没有问题，
这是为什么呢？
<img width="783" alt="截屏2023-05-17 00 31 17" src="https://github.com/chenbinghui1/DSL/assets/100546897/0fc6023d-8cea-40dc-9e80-07a0de3ed850">

**Comment by PilgrimGrey1** [comment]
> 我准备去修改每个epoch的训练流程，发现源代码semi_epoch_based_runner.py中的run函数在进行epoch循环的时候有问题：
> <img alt="截屏2023-05-17 00 28 23" width="642" src="https://user-images.githubusercontent.com/100546897/238711481-ba2067ab-3d34-402b-82bc-e91cc62fa2cc.png">
> 每次执行该文件夹下的train函数的时候，是self._epoch+=1，但在run函数中，是拿self.epoch进行判定，程序执行却没有问题，
> 这是为什么呢？
> <img alt="截屏2023-05-17 00 31 17" width="783" src="https://user-images.githubusercontent.com/100546897/238711908-0fc6023d-8cea-40dc-9e80-07a0de3ed850.png">

是不是在继承类epochbasedrunner中，规定这两者是一样的？
