### ISSUE TITLE
关于unlabel_train.sh

### ISSUE THREAD

**Issue by DaiHonghao** [chenbinghui1/DSL#31]
关于unlabel_train.sh脚本文件的问题，想要复现大佬的项目，但是发现在DEMO目录下并没有此文件，请问在哪个目录下呢？可以帮忙解决一下吗

**Comment by chenbinghui1** [comment]
@caigouDHH  unlabel_dynamic.sh

**Comment by DaiHonghao** [comment]
感谢您的解答！
