### ISSUE TITLE
伪标签好像没有及时更新？

### ISSUE THREAD

**Issue by SouthMaiya** [chenbinghui1/DSL#32]
在训练过程中预测伪标签的时候，我看到预测的图是：[self.image_list[next_iter]]，也就是说每一个iteration只更新一张伪标签吗？还是我的理解的问题，期待你的回答，万分感激

**Comment by chenbinghui1** [comment]
@SouthMaiya  关于伪标签更新，code是基于batch=2（per GPU）的写的，也就是一个iter内只有一个无标注数据，如果batch per GPU更大或者有自行组合的比例，可以适当修改伪标签更新相关的code

**Comment by SouthMaiya** [comment]
好的，谢谢。我看到code里的下一个待预测的无标注数据是从这个来的：next_iter = next(runner.ITER)，但我没找到runner.ITER是从哪里来的，想请教一下从哪里入手。

**Comment by chenbinghui1** [comment]
@SouthMaiya 一般runner相关的 会在 mmdet/runner/hook/下
https://github.com/chenbinghui1/DSL/blob/f06a4112fd708185323363891df1e3d938982b19/mmdet/runner/hooks/semi_epoch_based_runner.py#L145
https://github.com/chenbinghui1/DSL/blob/f06a4112fd708185323363891df1e3d938982b19/mmdet/runner/hooks/sampler_seed.py#L10-L11

**Comment by SouthMaiya** [comment]
哇，感谢感谢，没注意到这个文件，谢谢大佬（在这里鞠个躬）。
