### ISSUE TITLE
复现没达到预期

### ISSUE THREAD

**Issue by PilgrimGrey1** [chenbinghui1/DSL#33]
这是我baseline的训练结果，用的10%的数据集
<img width="1585" alt="截屏2023-03-30 11 05 43" src="https://github.com/chenbinghui1/DSL/assets/100546897/6d4b0dc3-e920-4db5-a3b8-fc2feaea9996">
这是我在上面的基础上跑EMA出现的结果，现在就发现似乎未标记数据对整个检测性能没有增强。
<img width="1584" alt="截屏2023-04-09 23 55 15" src="https://github.com/chenbinghui1/DSL/assets/100546897/e57b4a41-0f2c-488a-b43e-e68e5c907f12">
这是我改进了之后的模型性能，还是发现未标记数据没有对性能造成提升，我想问一下，4张3090，总内存30G，8个cpu核心，应该不会存在运算过程中的信息丢失的问题，但是就是跑不出来，您能够给我一些建议吗？我现在想是否是数据集的问题，过大，我换个小众数据集
<img width="991" alt="截屏2023-05-23 19 18 35" src="https://github.com/chenbinghui1/DSL/assets/100546897/5dd46934-7046-40ce-a90c-8cf940c9a836">

**Comment by PilgrimGrey1** [comment]
> 这是我baseline的训练结果，用的10%的数据集
> <img alt="截屏2023-03-30 11 05 43" width="1585" src="https://user-images.githubusercontent.com/100546897/241355941-6d4b0dc3-e920-4db5-a3b8-fc2feaea9996.png">
> 这是我在上面的基础上跑EMA出现的结果，现在就发现似乎未标记数据对整个检测性能没有增强。
> <img alt="截屏2023-04-09 23 55 15" width="1584" src="https://user-images.githubusercontent.com/100546897/241355945-e57b4a41-0f2c-488a-b43e-e68e5c907f12.png">
> 这是我改进了之后的模型性能，还是发现未标记数据没有对性能造成提升，我想问一下，4张3090，总内存30G，8个cpu核心，应该不会存在运算过程中的信息丢失的问题，但是就是跑不出来，您能够给我一些建议吗？我现在想是否是数据集的问题，过大，我换个小众数据集
> <img alt="截屏2023-05-23 19 18 35" width="991" src="https://user-images.githubusercontent.com/100546897/241355947-5dd46934-7046-40ce-a90c-8cf940c9a836.png">

期间我出现过，Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1808000 milliseconds before timing out.这个问题，最后我改了import torch.distributed as dist
dist.init_process_group(backend='nccl', timeout=<new_timeout_in_seconds>)中的运行时间限制

**Comment by PilgrimGrey1** [comment]
> 

能否提供一下最后的输出结果，我看看是不是过拟合了

**Comment by chenbinghui1** [comment]
@PilgrimGrey1 请问是只用了 EMA网络？无标记数据是怎么加入的，用的什么数据增广？每个batch分配情况是怎么样？ 用了90%无标记数据 在我的实验中是不太会出现过拟合的哈 ；

**Comment by chenbinghui1** [comment]
@PilgrimGrey1 
 另外检查下，每个iter 用到的unlabel数据以及对应的标签 可以vis一下看看 是否对。

**Comment by PilgrimGrey1** [comment]
> @PilgrimGrey1 请问是只用了 EMA网络？无标记数据是怎么加入的，用的什么数据增广？每个batch分配情况是怎么样？ 用了90%无标记数据 在我的实验中是不太会出现过拟合的哈 ；

这些我都是按照您的方式来的，按照readme，最后EMA的输出结果也是第7步中训练DSL得到的结果

**Comment by chenbinghui1** [comment]
建议你逐步debug下 还是刚才说的 检查下 每个iter的unlabel数据读取以及对应的伪标签什么的是否正确。毕竟 你是4卡3090 和我的不一样，不知道哪里修改了什么。 大概率是config不对。详细对比下原始config gpu数量引起的问题 我已经尽量在可能由于gpu数量导致的参数配置不一致的地方注释了

**Comment by lzx101** [comment]
你好，想问一下demo/model_train/unlabel_train.sh是否改成unlabel_dynamic.sh

**Comment by PilgrimGrey1** [comment]
> 你好，想问一下demo/model_train/unlabel_train.sh是否改成unlabel_dynamic.sh

是的是的，得修改

**Comment by kv1830** [comment]
你好，最后你复现出来了吗？

**Comment by lzx101** [comment]
感谢

**Comment by lzx101** [comment]
大佬你好，我想知道聚合教师具体是哪一块的内容啊
