### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by 1icas** [chenbinghui1/DSL#4]
連不上外網，請問可以放到baidu網盤上面嗎

**Comment by chenbinghui1** [comment]
@1icas   https://pan.baidu.com/s/1GrNxNariVpb9S5EUFW1eng   Extract Code: 5lf1

**Comment by 1icas** [comment]
> @1icas https://pan.baidu.com/s/1GrNxNariVpb9S5EUFW1eng Extract Code: 5lf1

感谢！

**Comment by chenbinghui1** [comment]
@1icas  If no other questions, this issue will be closed
