### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by weyoung0** [chenbinghui1/DSL#6]
请问安装好4个依赖后就可以直接运行代码了吗？是否需要pip install -v 之类的命令？

**Comment by weyoung0** [comment]
大佬能否给一份详细一点的install教程，比如InstantTeaching这种？
```
conda create -n instant_teaching python=3.7 -y
conda activate instant_teaching
conda install pytorch=1.7.1 torchvision cudatoolkit=10.1 -c pytorch
pip install mmcv==1.2.4

git clone http://gitlab.alibaba-inc.com/jianchong.zq/InstantTeaching.git
cd InstantTeaching
pip install -v -e .
```
感激不尽！

**Comment by chenbinghui1** [comment]
@weyoung0 类似mmdet 安装 https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md  只是个环境罢了，环境装好，然后clone项目 cd到目录里面 pip install -v -e . 或者 python setup.py develop

**Comment by weyoung0** [comment]
感谢大佬，环境装好了，换自己数据集跑跑看

**Comment by chenbinghui1** [comment]
@weyoung0 好的 祝贺~ 自己数据的话 根据unlabel数据和label数据个数的比例  调整unlabel loss weight，若出现nan的loss 说明weight大了，可以调小些，我的经验是比例大于3：可以用weight=3 若比例是1，weight=1，若比例是2左右weight=2或者1.5就够了

**Comment by chenbinghui1** [comment]
@weyoung0 好的 祝贺~ 自己数据的话 根据unlabel数据和label数据个数的比例  调整unlabel loss weight，若出现nan的loss 说明weight大了，可以调小些，我的经验是比例大于3：可以用weight=3 若比例是1，weight=1，若比例是2左右weight=2或者1.5就够了
