### ISSUE TITLE
May I ask if you have released all the code?

### ISSUE THREAD

**Issue by SouthMaiya** [chenbinghui1/DSL#7]
您好，我在复现的过程中发现代码里没有demo/model_train/unlabel.sh这个文件，在论文里面涉及的一些方法我也没有找到相关的代码，请问您是已经把所有核心代码都放了吗？我用demo/model_train/unlabel_dynamic.sh文件训练的时候代码似乎是有bug

**Comment by chenbinghui1** [comment]
@SouthMaiya  不知道你要找的是哪部分代码？ 另外我们只提供了demo/model_train/unlabel_dynamic.sh这个用于训练 好像并没有提到你说的demo/model_train/unlabel.sh  其次bug可否提供下 我这边是没有bug的

**Comment by SouthMaiya** [comment]
非常感谢您的回复，demo/model_train/unlabel.sh是在readme里写的训练文件，不知道如何找到MetaNet和 Aggregated Teacher的代码？关于bug，我查看了下，输入fcos检测器的img和gt的数量不对应，但是在dataloader出来的数量是对应的呀，请问可能是什么原因呢？
(Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  & (flatten_labels < bg_class_ind)).nonzero().reshape(-1)
Traceback (most recent call last):
  File "./tools/train.py", line 202, in <module>
    main()
  File "./tools/train.py", line 198, in main
    ema_model = ema_model)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/apis/train.py", line 222, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/runner/hooks/semi_epoch_based_runner.py", line 346, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/runner/hooks/semi_epoch_based_runner.py", line 267, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/runner/hooks/semi_epoch_based_runner.py", line 156, in run_iter
    **kwargs)
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/models/detectors/single_stage.py", line 85, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/models/dense_heads/fcos_head.py", line 310, in loss
    flatten_cls_scores, flatten_labels, weight = weight, avg_factor=num_pos)
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/models/losses/focal_loss.py", line 178, in forward
    avg_factor=avg_factor)
  File "/media/zxq/store/pycharm_Projects/Work/work3_semi/DSL-main/mmdet/models/losses/focal_loss.py", line 87, in sigmoid_focal_loss
    'none')
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/site-packages/mmcv/ops/focal_loss.py", line 40, in forward
    assert input.size(0) == target.size(0)
AssertionError
Traceback (most recent call last):
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/zxq/anaconda3/envs/dsl_mmdet/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zxq/anaconda3/envs/dsl_mmdet/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/fcos_semi/voc/RLA_r50_caffe_mslonger_tricks_0.Xdata_unlabel_dynamic_lw_nofuse_iterlabel_si-soft_singlestage.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/voc_dsl/0.1data']' returned non-zero exit status 1.

**Comment by chenbinghui1** [comment]
@SouthMaiya emmm难道我们看的不是一个readme？ 我还想还是没找到 哪里有说到unlabel.sh  我们只提供了unlabel_train.sh  另外请问是按照steps来弄的吧？用的环境或者数据是一样的嘛？还有config除了数据路径 有修改嘛？关于MetaNet和data flow我们进行了优化，我们在release版本去掉了MetaNet，通过优化dataflow 可以加速很多，且效果也差不多。

**Comment by SouthMaiya** [comment]
> @SouthMaiya emmm难道我们看的不是一个readme？ 我好像还是没找到 哪里有说到unlabel.sh 我们只提供了unlabel_train.sh 另外请问是按照steps来弄的嘛？用的环境或者数据是一样的嘛？还有config除了数据路径 有修改别的吗嘛？关于MetaNet和dataflow我们进行了优化，我们在release版本去掉了MetaNet，通过优化dataflow 可以加速很多，且效果也差不多。Aggregated Teacher 是通过EMAHook + resnet_rla.py联合实现的

那就是unlabel_dynamic.sh就是训练脚本是吧？我只修改了相关的路径，其他的没有改，关于这个bug，我在代码里看到在mmdet/runner/hooks/semi_epoch_based_runner.py里面第193行：
                tmp = torch.zeros_like(data_batch['img'].data[0][1:,:,:,:])
                _,_,h,w = data_batch['img'].data[0].shape
                cdata = torch.nn.functional.interpolate(data_batch['img'].data[0][1:,:,:,:].clone(), (int(h/2),int(w/2)), mode='bilinear')
                tmp[:,:,:int(h/2),:int(w/2)] = cdata
                data_batch['img'].data[0] = torch.cat((data_batch['img'].data[0],tmp),0)

                data_batch['gt_bboxes'].data[0].append(data_batch['gt_bboxes'].data[0][-1].clone()/2)
                data_batch['gt_labels'].data[0].append(data_batch['gt_labels'].data[0][-1].clone())
                data_batch['gt_bboxes_ignore'].data[0].append(data_batch['gt_bboxes_ignore'].data[0][-1].clone())
                if len(data_batch['gt_bboxes_ignore'].data[0][-1])>0:
                        data_batch['gt_bboxes_ignore'].data[0][-1]=data_batch['gt_bboxes_ignore'].data[0][-1]/2
这个部分的数据处理，输入的img扩充了bs-1个，但是相应的gt_bbox只增添了一个，所以出现输入的数据Img数量和gt不对应，请问是我这边的问题吗？关于MetaNet，请问dataflow指的是？

**Comment by chenbinghui1** [comment]
@SouthMaiya 如果每张卡用2张图的话 那就是只补充了一张图进去，是没有问题，这张图就是用于计算Lscale的；另外MetaNet是去掉了，和dataflow无关；dataflow指的是输入数据的个数，可以看paper种输入的图是三张无标注图片，而我们这边是优化成2张无标注图了，更简洁了。

**Comment by SouthMaiya** [comment]
> @SouthMaiya 如果每张卡用2张图的话 那就是只补充了一张图进去，是没有问题，这张图就是用于计算Lscale的；另外MetaNet是去掉了，和dataflow无关；dataflow指的是输入数据的个数，可以看paper种输入的图是三张无标注图片，而我们这边是优化成2张无标注图了，更简洁了。

感谢感谢，我的bs设置的是6，那我相应的改一下，谢谢！

**Comment by chenbinghui1** [comment]
@SouthMaiya 嗯BS多的话 把图片扩充的那个地方 改成-1就行了

**Comment by yarkable** [comment]
我也遇到了这个问题，感谢作者的回复！

**Comment by yarkable** [comment]
请问如果我只有4张卡，设置了samples_per_gpu=4的话应该更改哪里呢？ @chenbinghui1

**Comment by yarkable** [comment]
@chenbinghui1 OK,我会去细看一下这段代码，但是如果我不需要L_scale的话是不是就不存在这个问题了呢？（也就是将scale_invariant=False）

**Comment by chenbinghui1** [comment]
@yarkable 是的呢

**Comment by yarkable** [comment]
@chenbinghui1 还想请教个问题，我对 multidataloader的流程看不太懂，请问一下每个batch他的labeled和unlabeled数据是如何送入网络的呢

**Comment by chenbinghui1** [comment]
@yarkable 关于ignore label，包含两段代码，第一段是你引用的这段，这段主要为了利用get_target的功能，得到ignore区域的相应label用于后续loss的计算；首先将ignore的区域的原始label设置为num_class-1, 调用get_target得到的ig_labels就是包含id=num_class-1的ignore区域以及id=num_class的背景区域； 第二段代码是这里
https://github.com/chenbinghui1/DSL/blob/4ea7bf043dbbd25f9c05ec32e599806a6a3d9790/mmdet/models/dense_heads/fcos_head.py#L298-L304
目的是利用得到的ig_label 将id为num_class-1的地方对应的weight设置为0 其他地方为1；这样weight就可以送到loss里面进行计算了

**Comment by chenbinghui1** [comment]
@yarkable 关于multidataloader；是类似重构了下dataloader的功能，首先它的输入包含多个datasets，然后会为每个dataset构建对应的dataloader，在每次调用__next__函数时候，会将每个dataloader的数据取出（此时包含多个DataContainer） 并且通过_merge_data2one_batch 函数merge成一个DataContainer，从而够成单个的tensor便于网络输入

**Comment by chenbinghui1** [comment]
@yarkable 关于multidataloader；是类似重构了下dataloader的功能，首先它的输入包含多个datasets，然后会为每个dataset构建对应的dataloader，在每次调用__next__函数时候，会将每个dataloader的数据取出（此时包含多个DataContainer） 并且通过_merge_data2one_batch 函数merge成一个DataContainer，从而够成单个的tensor便于网络输入

**Comment by chenbinghui1** [comment]
@yarkable 关于multidataloader；是类似重构了下dataloader的功能，首先它的输入包含多个datasets，然后会为每个dataset构建对应的dataloader，在每次调用__next__函数时候，会将每个dataloader的数据取出（此时包含多个DataContainer） 并且通过_merge_data2one_batch 函数merge成一个DataContainer，从而够成单个的tensor便于网络输入；
另外 控制一个batch中label和unlabel数据个数的是这里https://github.com/chenbinghui1/DSL/blob/4ea7bf043dbbd25f9c05ec32e599806a6a3d9790/configs/fcos_semi/RLA_r50_caffe_mslonger_tricks_0.Xdata_unlabel_dynamic_lw_nofuse_iterlabel_si-soft_singlestage.py#L124
可以通过修改ratio数值来进行控制；当前是[[1,1],]表示为1：1

**Comment by yarkable** [comment]
> 

感谢，非常清晰的回答！

**Comment by yarkable** [comment]
@chenbinghui1 
您的回复解开了我很多疑惑，不过我还有亿些问题想请教一下：
1. 关于multidataloader的话，我如果有三个数据集，似乎修改一下就能复用这个dataloader了吧。
2. 另外，这个 ratio 为啥要用二维列表的形式来存储呢，是这套代码有其他的应用场景嘛还是怎样，因为我看代码里面 len(ratio) 始终都是 1 的， self.concat 恒为 True。而且我个人感觉用 ratio 来表示的话似乎会有些难以理解？因为他其实是有点 sample 的意思，如果 sample_per_gpu 为 4 的话，这里应该是 [[2,2]] 对吧。

**Comment by chenbinghui1** [comment]
@yarkable 
1.  是的 核心不用动，只需要修改 输入的datasets里面的内容即可，
https://github.com/chenbinghui1/DSL/blob/0dfe79b27798b18fb7a0eb0dec39cc14751572c8/mmdet/apis/train.py#L78-L86
2. 是的 这套代码可以支持很多情形，例如>2的dataset，还有些其他的混合dataset情形；代码中 对ratio的计算是按照归一化比例来算的 所以 sample_per_gpu=4的话 写[[2,2],]也行 写[[1,1],]也可以

**Comment by yarkable** [comment]
@chenbinghui1 
hello，对 inter_inds 这部分，我的理解是：
`
对 unlabeled image 来说，找到匹配质量不太好的（ignore）anchor，再看看这部分 anchor 是否匹配了 labeled image 中的 gt_bbox，如果同时匹配到的话，就在计算 unlabeled loss 的时候不对这个 anchor 进行忽略（weight=1）
`
https://github.com/chenbinghui1/DSL/blob/0dfe79b27798b18fb7a0eb0dec39cc14751572c8/mmdet/models/dense_heads/fcos_head.py#L300-L301

不知道我的理解是否正确，以及在我 debug 的过程中发现 inter_inds 经常是空的，也就是说不怎么会出现上述情况，请问引入这个是出于什么考虑呢

**Comment by chenbinghui1** [comment]
@yarkable  你的理解部分是对的，但是只是针对unlabel image自己的；因为labeled image对应输出的ignore_label应该都是背景；这样设计的目的就是为了处理unlabel image中遮挡目标的问题，例如一个分数较低的和分数较高的两个框是有overlap的。

**Comment by yarkable** [comment]
@chenbinghui1 
感谢指正，另外，我发现其实还需要给 unlabeled image 一个 initial 的 annotation（我最初以为是跟 Soft-teacher那样端到端的），请问可以不用这个步骤，直接用baseline model推理伪标签吗，其实我想做的是 Partially labeled datasets collaborate training，也就是类似将 VOC 和 COCO 加在一起训练的

**Comment by chenbinghui1** [comment]
@yarkable ,是的 需要初始化 （从效果来看）；Soft-teacher 其实也差不多 ，只不过不同于具体的代码实现，但是本质都是一样的，初期会有一段只有label数据作用的阶段；当前代码其实也可以实现，初期unlabel的annotfile里面都设置为空的，例如rect:[]，然后将unlabel_pred 中的start参数提前一些即可，同时修改下代码增加一个不更新伪标签的epoch个数的参数，在这个周期内最好不要动态更新标签，因为这个时候主要是让基础模型的能力先提高一下从而达到一个可信的基准，伪标签的精准度主要是后期体现出来，提前更新伪标签 反而会让基础模型拿不准，导致收敛又难又慢；  我之前试过对于anchor-free检测器来说前期采用一个固定的pseudo-label要比动态更新的pseudo-label效果好

**Comment by yarkable** [comment]
@chenbinghui1 
感谢回复，关于代码对这部分的流程，我的理解是这样的，不知道是否正确。
> 首先会将 labeled image 的 gt 和 unlabeled image 的 initial pseudo label 一起进行 training，这个过程中 unlabeled image 的 pseudo label 并不会得到更新。在训练了一定的 epoch 之后（代码中是 8 epoch），每一个epoch 训完后，会调用 UnlabelpredHook 对原来的标签进行更新，所以下次拿到的 pseudo label 是经过 refine 后的。
2. 关于 UnlabelpredHook，虽然我的猜想如上面所示，但是我暂时没能够进去 debug 看看每一步在干啥（因为报错退出了），感觉对下面的这部分有些难以理解，看上去是每一个 iter 都会更新一遍伪标签？这样不会很耗时嘛；以及 iter_fuse_flag 这个 flag 是用来判断什么逻辑的呢；这里的 runner.ITER 是提前将数据导入节省时间还是怎样呢，不是很明白为什么在这个 hook 里面要有这个流程，希望指点一番！
https://github.com/chenbinghui1/DSL/blob/0dfe79b27798b18fb7a0eb0dec39cc14751572c8/mmdet/runner/hooks/unlabel_pred_hook.py#L447-L469

**Comment by yarkable** [comment]
@chenbinghui1 或者有什么方便的方法让我进去 UnlabelpredHook 嘛，我试过将 after_train_iter 改成 before_train_iter 没有用

**Comment by chenbinghui1** [comment]
@yarkable  Ok 明白你的意思了，你的理解大致是对的。我再详细解释下哈 首先 这个unlabelpredhook支持 两种方式的更新，一个是基于epoch的一个是基于iter的；
（1）对于epoch的你的理解是对的，每个epoch结束的时候会进行伪标签的打标；
（2）对于iter的 稍微有些麻烦；这部分里面的runner.ITER是为了保证每次iter结束后进行伪标签更新的图片是和下一个iter所训练的图片是一致的（因为mmdet里面有preload机制，preload是为了提高IO的使用效率，所以如果要实现基于iter的unlabelpred 必须考虑这个preload的问题，不然每次更新的图片相当于下一次dataload里面的图片已经滞后很多了，当然可能有更好的实现方式哈，嘿嘿 我这里为了用同一个predhook就这样实现了）；

其次 这个unlabelpredhook其实还支持历史伪标签的融合策略（参考论文中提到的ISMT[48]论文），具体就是，当前更新的标签是否要和历史标签进行NMS的融合；那么这个时候就会用到iter_fuse_flag这个flag，因为 整个unlabelpredhook会有个start_point的参数，如果它的值较大，那么当开始进行伪标签更新的时候，可能历史的伪标签就相对不那么准了，会影响融合结果，所以会在第一更新的时候傻瓜式调用self.after_train_epoch_iter(runner) 来将所有图片的伪标签更新一下，从而提高后续标签融合的效果。

**Comment by chenbinghui1** [comment]
@yarkable 可以通过修改after_train_iter 或者修改after_train_epoch 来调用自己想要的函数。

**Comment by yarkable** [comment]
@chenbinghui1 对，也就是说到一定epoch之后，每一个 iter 和 每一个 epoch 之后都会更新伪标签，对吧

**Comment by chenbinghui1** [comment]
@yarkable emm不是的 看选择的mode是什么了 如果是“epoch” 那只在每个epoch后更新，如果mode=‘iteration’ 只会在第一次更新的时候调用self.after_train_epoch_iter(runner)  然后就是每个iter更新了 epoch结束后就直接到下个epoch了

**Comment by yarkable** [comment]
@chenbinghui1 我看默认的是‘iteration’，请问实际上的话哪种效果更好些呢

**Comment by chenbinghui1** [comment]
@yarkable 对于coco和voc来说是iter会更好；我们也在自己的业务数据上做了 epoch会更好（可能数据少的原因）

**Comment by yarkable** [comment]
@chenbinghui1 OK，但还是那个问题，速度不会很慢吗，每一个iter都推理的话；我试过coco 10%数据推理一遍要十五分钟左右，一个epoch有十几万个iter，请问你们怎么解决这个问题的呢

**Comment by chenbinghui1** [comment]
@yarkable 每个iter 只推理下个iter 的图片 不是所有图片都推理

**Comment by yarkable** [comment]
@chenbinghui1 原来如此，多谢！

**Comment by yarkable** [comment]
@chenbinghui1 最后再问一下，单 COCO 的话八卡大概要跑多久呀，有个心理预期。

**Comment by chenbinghui1** [comment]
@yarkable 我这边10%数据的话，V100 8卡 大概两天半到三天；

**Comment by yarkable** [comment]
很顶

**Comment by yarkable** [comment]
@chenbinghui1 
hello，我对代码还有些疑问，一个是在 unlabel_pred_hook 中，这边的sub_dir是为啥呢，看了代码感觉跟我之前的理解不太一样，之前我理解这个hook的流程是在`unlabel_prepared_annos/Industry/annotations/full/`中找到那张unlabeled图片对应的json并对其进行更新，但这里好像还加了一些新的key，看得有点晕，希望指教一下。
```python
def save_results2file(result, image_path, image_height, image_width,
                      save_file_format, checkpoint_name, infer_score_thre,
                      id2cat, cat2id, image_root_path, save_root_path,
                      task_type, vis=False, save_polygon=False, anno_root_path=None, iou=0.1, fuse=False, first_ignore=False):
    '''
    self.image_root_path = kwargs["image_root_path"]    # data_root + "images/full/"
    self.image_list_file = kwargs["image_list_file"]    # 'data_list/coco_semi/semi_supervised/instances_train2017.3@10-unlabeled.json'
    self.anno_root_path = kwargs["anno_root_path"]      # data_root + "unlabel_prepared_annos/Industry/annotations/full/"
    '''
    # zhoujing.zjh 防止image_root_path以/结尾导致图像层级目录个数判断错误，导致保存的结果中缺少dataset
    image_root_path = os.path.abspath(image_root_path)  # '/home/tiger/DSL/data/semicoco/images/full'
    image_name = image_path.split('/')[-1]  # 
    sub_path = image_path.replace(image_root_path, "")
    sub_dirs = sub_path.split("/")[:-1]
    #assert 3 > len(sub_dirs) > 0, \
    #    "[Error][ModelInfer] Please check image_root_path for inference."
    for sub_dir in sub_dirs:
        #image_name = os.path.join(sub_dir, image_name)
        save_path = os.path.join(save_root_path, sub_dir)
        create_dir(save_path)

    if save_file_format == "json":
        save_path = os.path.join(save_path, image_name + ".json")
        info_dict = dict()
        if len(sub_dirs) == 2:
            info_dict["dataset_name"] = sub_dirs[-1]
        else:
            info_dict["dataset_name"] = ''
        info_dict["checkpoint_name"] = checkpoint_name
        info_dict["image_name"] = image_name
        info_dict["image_height"] = image_height
        info_dict["image_width"] = image_width
        info_dict["result"] = result
        info_dict["task_type"] = task_type
        info_dict["infer_score_thre"] = infer_score_thre
        dict_save = gen_save_json_dict(info_dict, save_root_path,
                                       reverse_mapper=id2cat,
                                       save_polygon=save_polygon)
        # bhchen fuse with old bboxes
        new_info=dict()
        new_info['targetNum'] = len(dict_save['infer_results'])
        new_info['rects'] = []
        new_info['scores'] = []
        new_info['tags'] = []
        new_info['cid'] = []
...
````


2. 另外，`generate_unlabel_annos_coco.py`这里是否写错了呢？imageName应该没有json的后缀吧
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/33142987/175857237-f2d52dcf-b9e3-48b2-a526-f04975c2b236.png">

**Comment by chenbinghui1** [comment]
@yarkable 
1. 没有新的keys增加啊，最终保存的是final_info
https://github.com/chenbinghui1/DSL/blob/0dfe79b27798b18fb7a0eb0dec39cc14751572c8/mmdet/runner/hooks/unlabel_pred_hook.py#L167-L175
2. 嗯 是的 可以修改一下，不过我记得代码中应该没有用到imageName这个字段，应该不会影响结果的；

**Comment by yarkable** [comment]
@chenbinghui1 明白，但是我执行这个hook的时候会报路径的错误，并且还生成了很多空的文件夹，感觉是哪里出了问题，所以对前面那些处理路径的代码不是特别懂
<img width="387" alt="image" src="https://user-images.githubusercontent.com/33142987/175875650-43e4c2b3-e9e8-4015-9cd6-74652c3f9d81.png">

**Comment by chenbinghui1** [comment]
@yarkable 是不是config里面路径写的不太对呢？怎么annotations/full、里面又生成了个semicoco 同级目录还有images-_-；

**Comment by yarkable** [comment]
@chenbinghui1 
我的data config应该和你是一样的
```python
dataset_type = 'SemiCOCODataset'
## DSL-style data root
data_root = 'data/semicoco/'

data = dict(
    samples_per_gpu=2,
    # if you change workers_per_gpu, please change preload below at the same time
    workers_per_gpu=2,
    batch_config=dict(ratio =[[1, 1],]),
    # 先去 data_list 中找到相应的 json 进行读取，在 json 找到每一个图片的 filename，然后去 semicoco 或者 semivoc 中读取单个图片的 json 标注文件
    train=dict(
        type=dataset_type,
        ann_file = 'data_list/coco_semi/semi_supervised/instances_train2017.3@10.json',
        ann_path = data_root + 'prepared_annos/Industry/annotations/full/', # 118287+5000张annotation
        labelmapper = data_root + 'mmdet_category_info.json',
        img_prefix = data_root + 'images/full/',
        pipeline = train_pipeline,
        ),
    unlabel_train=dict(
        type=dataset_type,
        ann_file = 'data_list/coco_semi/semi_supervised/instances_train2017.3@10-unlabeled.json',
        ann_path = data_root + 'unlabel_prepared_annos/Industry/annotations/full/',
        labelmapper = data_root + 'mmdet_category_info.json',
        img_prefix = data_root + 'images/full/',
        pipeline = unlabel_train_pipeline,
        # fixed thres like [0.1, 0.4]; or ada thres
        thres="adathres.json",
        ),
    unlabel_pred=dict(
        type=dataset_type,
        num_gpus = 4,
        image_root_path = data_root + "images/full/",
        image_list_file = 'data_list/coco_semi/semi_supervised/instances_train2017.3@10-unlabeled.json',
        anno_root_path = data_root + "unlabel_prepared_annos/Industry/annotations/full/",
        category_info_path = data_root + 'mmdet_category_info.json',
        infer_score_thre=0.1,
        save_file_format="json",
        pipeline = test_pipeline,
        eval_config ={"iou":[0.6]},
        img_path = data_root + "images/full/",
        img_resize_size = (1333,800),
        low_level_scale = 16,
        use_ema=True,
        eval_flip=False,
        fuse_history=False, # as ISMT fuse history bboxes by nms
        first_fuse=False,
        first_score_thre=0.1,
        # 涉及到伪标签的更新模式
        # eval_checkpoint_config=dict(interval=1, mode="iteration"),
        eval_checkpoint_config=dict(interval=1, mode="epoch"),
        # 2*num_worker+2
        preload=6,
        #the start epoch; partial data use 8; alldata don't use by setting 100
        start_point=0), # 8
    val=dict(
        type = 'CocoDataset',
        ann_file = 'data_list/coco_semi/semi_supervised/instances_val2017.json',
        img_prefix = data_root + 'valid_images/full/',
        pipeline = test_pipeline,
        ),
    test=dict(
        type = 'CocoDataset',
        ann_file = 'data_list/coco_semi/semi_supervised/instances_val2017.json',
        img_prefix = data_root + 'valid_images/full/',
        pipeline = test_pipeline,
        )
```

**Comment by chenbinghui1** [comment]
@yarkable  大概知道了 data_root = 'data/semicoco/' 这里请用 绝对路径试试

**Comment by yarkable** [comment]
@chenbinghui1 确实是这个问题，折磨好久，现在终于把流程走完了hh

**Comment by yarkable** [comment]
@chenbinghui1 十分感谢作者快速的回复，以后可能还会有写问题来请教一下[抱拳]

**Comment by yarkable** [comment]
@chenbinghui1 hello，国庆快乐，请问有试过将这个方法放到faster rcnn上做实验嘛，我简单替换 config 里面的 model 似乎不行，因为faster在第二阶段才涉及伪标签的正负样本以及忽略样本。如果有试过的话可以告知一下怎么改动比较方便吗

**Comment by chenbinghui1** [comment]
@yarkable 如论文所说，我们这个工作主要针对anchor-free 的检测器，并且是主要用到实际项目中的，所以没有关注过faster-rcnn的适配。

**Comment by yarkable** [comment]
@chenbinghui1  OK 感谢
